
unclassified:
  location:
    url: http://localhost:8080/

jobs:
  - script: |
      pipelineJob('cpp-cicd-poc') {
        def repo = 'https://github.com/ahlrothanton/cpp-cicd-poc.git'
        description("C++ CICD PoC Jenkins job.")
        definition {
          cpsScm {
            scm {
              git {
                remote { url(repo) }
                branches('main')
                scriptPath('cicd/jenkins/Jenkinsfile')
                extensions { }
              }
            }
          }
        }
      }